// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// lat2row
int lat2row(double lat);
RcppExport SEXP isin_lat2row(SEXP latSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    rcpp_result_gen = Rcpp::wrap(lat2row(lat));
    return rcpp_result_gen;
END_RCPP
}
// rowlon2bin
int rowlon2bin(int row, double lon);
RcppExport SEXP isin_rowlon2bin(SEXP rowSEXP, SEXP lonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type row(rowSEXP);
    Rcpp::traits::input_parameter< double >::type lon(lonSEXP);
    rcpp_result_gen = Rcpp::wrap(rowlon2bin(row, lon));
    return rcpp_result_gen;
END_RCPP
}
// latlon2bin
Rcpp::DataFrame latlon2bin(NumericVector lat, NumericVector lon);
RcppExport SEXP isin_latlon2bin(SEXP latSEXP, SEXP lonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP);
    rcpp_result_gen = Rcpp::wrap(latlon2bin(lat, lon));
    return rcpp_result_gen;
END_RCPP
}
// bin2latlon
Rcpp::DataFrame bin2latlon(NumericVector binIndex);
RcppExport SEXP isin_bin2latlon(SEXP binIndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type binIndex(binIndexSEXP);
    rcpp_result_gen = Rcpp::wrap(bin2latlon(binIndex));
    return rcpp_result_gen;
END_RCPP
}
